### ISSUE TITLE
using an https url

### ISSUE THREAD

**Issue by barmstrong** [chrisk/fakeweb#35]
We were trying to register an https url (just to match the actual one used) and got this error:

```
FakeWeb.register_uri(method, "https://example.com/api/v1/account/balance", body: body.to_json)

 Failure/Error: Net::HTTP.get(URI.parse("https://example.com/api/v1/account/balance"))
 SocketError:
   getaddrinfo: nodename nor servname provided, or not known
```

If we remove the https, it works.  Not a big deal but was just curious if there was an easy way to add https or why it didn't work. Thanks for the great gem!
